### ISSUE TITLE
Stacking http.Handle routers

### ISSUE THREAD

**Issue by utrack** [sclevine/infuse#2]
Hey!
I'm trying to stack julienschmidt/httprouter on top of infuse and it doesn't work; can't figure why.
Adapted listing from Examples works, but if I try to use something like that:

```
    handler := infuse.New().StackFunc(mymiddleware)
    router := httprouter.New()
    router.GET("/i", handlers.IndexParams)
    ih.Stack(router)
```

I get empty page with code 200.

**Comment by sclevine** [comment]
For the last line, did you mean `handler.Stack(router)`?

**Comment by utrack** [comment]
@sclevine yes, typo in the example.
Figured out the problem after two hours of troubleshooting, used

```
ih.Stack(router)
return ih
```

instead of

```
return ih.Stack(router)
```

so router wasn't really included in chain and the problem is on my end.
Sorry, guess the issue can be closed.

**Comment by sclevine** [comment]
No worries! Feel free to reach out if you have any more questions/suggestions.
