### ISSUE TITLE
Wrapped http.ResponseWriter gets lost

### ISSUE THREAD

**Issue by utrack** [sclevine/infuse#4]
It looks like if ResponseWriter had been wrapped in one of the middlewares as in example, nothing ever gets written to client.
Also, WriteHeader of a wrapper is never called (even if explicitly called in next MW).

```
// statusLoggingResponseWriter is a wrapper for ResponseWriter which
// logs written status code.
type statusLoggingResponseWriter struct {
    status int
    http.ResponseWriter
}

func (w *statusLoggingResponseWriter) WriteHeader(code int) {
    w.status = code
    w.ResponseWriter.WriteHeader(code)
    // Should trigger but doesn't
    fmt.Println("WriteHeader called")
}

// Stats middleware logs requests and responses.
func Stats() func(response http.ResponseWriter, request *http.Request) {
    return func(response http.ResponseWriter, request *http.Request) {
        // Let chain work
        myW := &statusLoggingResponseWriter{-1,response}
        infuse.Next(myW, request)
        fmt.Println(myW.status)
    }
}
```

**Comment by sclevine** [comment]
Hi @utrack, thanks for the report!

Actually, `infuse.Next(myW, request)` does not call the next handler in the chain at all, and returns false.
See: https://godoc.org/github.com/sclevine/infuse#Next

Infuse stores both the context value and the remaining middleware handlers by wrapping the initial `http.ResponseWriter` provided to the `infuse.Handler`. This means that you must pass the same `http.ResponseWriter` that the handler was called with to `infuse.Next`.

We could potentially use reflection to figure out if the `http.ResponseWriter` passed to `infuse.Next` contains an embedded `http.ResponseWriter` that has a context value and list of remaining handlers. We could even do this recursively if we don't find one immediately. This would be very complicated and add lots of complexity to infuse. It also wouldn't work if you wrapped the original `http.ResponseWriter` by some other method than embedding.

Alternatively, you could use `infuse.Set` to store the `status` you mention above. Infuse is already doing all of the work that you're doing in your example (and more).

The primary reason I don't want to implement this (and feel that using the context value is the more ideal solution) is that your `statusLoggingResponseWriter` breaks the handler's ability to use the provided response as an `http.CloseNotifier`, `http.Flusher`, or `http.Hijacker`. As your method for storing the status already breaks standard library functionality (for both `http.response`s and `http.ResponseRecorders`, in the case of `http.Flusher`), I don't feel like infuse needs to support it.

Do `infuse.Get` and `infuse.Set` not address your use case?

**Comment by sclevine** [comment]
I'm closing this issue, but feel free to re-open it if you disagree.

**Comment by utrack** [comment]
Sorry! I forgot about this issue. Well, it can be done with .Get and .Set, but if something fails and panics I can't be sure what HTTP code was really sent...

It's OK to close, I'll play with the sources and send a PR if I'll figure something out. :+1:
